# Identifier [name, icon, difficulty, description]
# Commented out goals are not yet implemented or are broken
index_version = '1.6.0'
goalDictionary = {
    # KILL GOALS
    "K0001": ['Kill 100 Mobs', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 1}', 1],
    "K0002": ['Kill Bee', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 2}', 1],
    "K0003": ['Kill Blue Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 3}', 1],
    "K0004": ['Kill Cave Spider', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 4}', 2],
    "K0005": ['Kill Cyan Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 5}', 2],
    "K0006": ['Kill Drowned', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 6}', 1],
    "K0007": ['Kill Elder Guardian', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 7}', 2],
    "K0008": ['Kill Endermite', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 8}', 3],
    "K0009": ['Kill Ghast', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 9}', 2],
    "K0010": ['Kill Green Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 10}', 2],
    "K0011": ['Kill Guardian', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 11}', 1],
    "K0012": ['Kill Husk', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 12}', 1],
    "K0013": ['Kill Light Blue Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 13}', 1],
    "K0014": ['Kill Lime Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 14}', 2],
    "K0015": ['Kill Magenta Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 15}', 1],
    "K0016": ['Kill Orange Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 16}', 1],
    "K0017": ['Kill Pink Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 17}', 1],
    "K0018": ['Kill Player', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 18}', 1],
    "K0019": ['Kill Purple Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 19}', 1],
    "K0020": ['Kill Red Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 20}', 1],
    "K0021": ['Kill Silverfish', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 21}', 3],
    "K0022": ['Kill Snow Golem', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 22}', 1],
    "K0023": ['Kill Spider', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 23}', 1],
    "K0024": ['Kill Stray', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 24}', 1],
    "K0025": ['Kill Witch', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 25}', 1],
    "K0026": ['Kill Wither Skeleton', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 26}', 2],
    "K0027": ['Kill 7 Unique Hostile Mobs', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 27}', 1],
    "K0028": ['Kill 15 Unique Hostile Mobs', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 28}', 2],
    "K0029": ['Kill Yellow Sheep', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 29}', 1],
    "K0030": ['Kill Zoglin', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 30}', 2],
    "K0031": ['Kill Zombie Villager', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 31}', 1],
    "K0032": ['Kill Zombie', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 32}', 1],
    "K0033": ['Kill Breeze', '"id": "minecraft:iron_sword"', 2],
    "K0034": ['Kill Blaze', '"id": "minecraft:iron_sword"', 2],
    "K0035": ['Kill Zombified Piglin', '"id": "minecraft:iron_sword","components": {"minecraft:custom_model_data": 35}', 1],
    "K0036": ['Kill Ender Dragon', '"id": "minecraft:dragon_head"', 4],
    "K0037": ['Kill Camel', '"id": "minecraft:cactus"', 2],
    "K0038": ['Kill Bogged', '"id": "minecraft:vine"', 1],
    "K0039": ['Kill Magma Cube', '"id": "minecraft:magma_cream"', 1],
    "K0040": ['Kill Warden', '"id": "minecraft:sculk_shrieker"', 4],
    "K0041": ['Kill Piglin Brute', '"id": "minecraft:golden_axe"', 2],
    "K0042": ['Kill Ravager', '"id": "minecraft:iron_sword"', 3],
    "K0043": ['Kill Slime', '"id": "minecraft:slime_block"', 2],
    "K0044": ['Kill Pillager', '"id": "minecraft:crossbow"', 2],
    "K0045": ['Kill Shulker', '"id": "minecraft:shulker_shell"', 4],

    # DIE GOALS
    "D0001": ['Die to Bee', '"id": "minecraft:beehive","components": {"minecraft:custom_model_data": 1}', 1],
    "D0002": ['Die to Iron Golem', '"id": "minecraft:carved_pumpkin","components": {"minecraft:custom_model_data": 1}', 1],
    "D0003": ['Die to Llama', '"id": "minecraft:hay_block","components": {"minecraft:custom_model_data": 1}', 1],
    "D0004": ['Die to Warden', '"id": "minecraft:sculk_shrieker"', 2],
    "D0005": ['Die to Witch', '"id": "minecraft:stick"', 2],
    "D0006": ['Die to Piglin Brute', '"id": "minecraft:golden_axe"', 2],
    "D0007": ['Die on Pointed Dripstone', '"id": "minecraft:pointed_dripstone"', 1],
    # "D0008": ['Die to TNT Minecart', '"id": "minecraft:tnt_minecart"', 1],
    "D0009": ['Die to Goat', '"id": "minecraft:goat_horn"', 3],
    "D0010": ['Die to Polar Bear', '"id": "minecraft:cod"', 2],

    # OPPONENT GOALS
    "N0001": ['Opponent Dies', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 2}', 1],
    "N0002": ['Opponent Obtains Crafting Table', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 1}', 1],
    "N0003": ['Opponent Takes Fall Damage', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 3}', 1],
    "N0004": ['Opponent Catches Fire', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 4}', 1],
    # "N0005": ['Opponent Jumps', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 5}', 1],
    "N0006": ['Opponent Obtains Obsidian', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 6}', 1],
    "N0007": ['Opponent Obtains Seeds', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 7}', 1],
    "N0008": ['Opponent Touches Water', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 8}', 1],
    "N0009": ['Opponent Wears Armor', '"id": "minecraft:barrier"', 1],
    "N0010": ['Opponent Takes 100 Damage', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 505063}', 1],
    "N0011": ['Opponent Dies 3 Times', '"id": "minecraft:barrier","components": {"minecraft:custom_model_data": 2}', 1],
    # "N0012": ['Have the Most Hoppers', '"id": "minecraft:hopper","components": {"minecraft:custom_model_data": 1}', 2],
    # "N0013": ['Have the Most Dried Kelp Blocks', '"id": "minecraft:hopper","components": {"minecraft:custom_model_data": 1}', 2],
    # "N0014": ['Opponent Obtains a Pickaxe', '"id": "minecraft:barrier"', 1],
    # ?"N0015": ['Use Spyglass on Opponent', '"id": "minecraft:spyglass"', 1],

    # TAME GOALS
    "T0001": ['Tame Cat', '"id": "minecraft:cod","components": {"minecraft:custom_model_data": 1}', 1],
    "T0002": ['Tame Horse', '"id": "minecraft:golden_carrot","components": {"minecraft:custom_model_data": 505063}', 1],
    "T0003": ['Tame Parrot', '"id": "minecraft:melon_seeds","components": {"minecraft:custom_model_data": 505063}', 2],
    "T0004": ['Tame Wolf', '"id": "minecraft:bone","components": {"minecraft:custom_model_data": 505063}', 1],
    "T0005": ['Tame Donkey', '"id": "minecraft:golden_carrot"', 1],
    "T0006": ['Tame Mule', '"id": "minecraft:golden_carrot"', 3],
    "T0007": ['Tame Llama', '"id": "minecraft:hay_block"', 1],

    # BREED GOALS
    "B0001": ['Breed Chicken', '"id": "minecraft:wheat_seeds","components": {"minecraft:custom_model_data": 1}', 1],
    "B0002": ['Breed Cow', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 2}', 1],
    "B0003": ['Breed Fox', '"id": "minecraft:sweet_berries","components": {"minecraft:custom_model_data": 505063}', 2],
    "B0004": ['Breed Goat', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 4}', 1],
    "B0005": ['Breed Hoglin', '"id": "minecraft:crimson_fungus","components": {"minecraft:custom_model_data": 1}', 2],
    "B0006": ['Breed Horse', '"id": "minecraft:golden_carrot","components": {"minecraft:custom_model_data": 2}', 1],
    "B0007": ['Breed Ocelot', '"id": "minecraft:cod","components": {"minecraft:custom_model_data": 2}', 2],
    "B0008": ['Breed Pig', '"id": "minecraft:carrot","components": {"minecraft:custom_model_data": 2}', 1],
    "B0009": ['Breed Rabbit', '"id": "minecraft:carrot","components": {"minecraft:custom_model_data": 1}', 1],
    "B0010": ['Breed Sheep', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 3}', 1],
    "B0011": ['Breed Strider', '"id": "minecraft:warped_fungus","components": {"minecraft:custom_model_data": 1}', 2],
    "B0012": ['Breed Axolotl', '"id": "minecraft:tropical_fish_bucket"', 2],
    "B0013": ['Breed 6 Unique Mobs', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 5}', 1],
    "B0014": ['Breed 8 Unique Mobs', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 5}', 2],
    "B0015": ['Breed Mooshroom', '"id": "minecraft:red_mushroom"', 3],
    "B0016": ['Breed Wolf', '"id": "minecraft:bone"', 2],
    "B0017": ['Breed Turtle', '"id": "minecraft:seagrass"', 1],
    "B0018": ['Breed Panda', '"id": "minecraft:bamboo"', 3],
    "B0019": ['Breed Armadillo', '"id": "minecraft:spider_eye"', 2],
    "B0020": ['Breed Frog', '"id": "minecraft:slime_ball"', 2],
    "B0021": ['Breed Sniffer', '"id": "minecraft:sniffer_egg"', 4],
    "B0022": ['Breed Cat', '"id": "minecraft:cod"', 2],
    "B0023": ['Breed 12 Unique Mobs', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 5}', 3],
    "B0024": ['Breed 15 Unique Mobs', '"id": "minecraft:wheat","components": {"minecraft:custom_model_data": 5}', 4],

    # ITEM GOALS
    "I0001": ['Obtain 5 Unique Saplings', '"id": "minecraft:oak_sapling","components": {"minecraft:custom_model_data": 505063}', 2],
    "I0002": ['Obtain All Hoes', '"id": "minecraft:netherite_hoe","components": {"minecraft:custom_model_data": 505063}', 3],
    "I0003": ['Obtain All Pickaxes', '"id": "minecraft:netherite_pickaxe","components": {"minecraft:custom_model_data": 505063}', 3],
    "I0004": ['Obtain All Rail Types', '"id": "minecraft:rail","components": {"minecraft:custom_model_data": 505063}', 1],
    "I0005": ['Obtain Armadillo Scute', '"id": "minecraft:armadillo_scute"', 1],
    "I0006": ['Obtain Cake', '"id": "minecraft:cake"', 1],
    "I0007": ['Obtain Chainmail Armor', '"id": "minecraft:chainmail_helmet"', 2],
    "I0008": ['Obtain Cobweb', '"id": "minecraft:cobweb"', 1],
    "I0009": ['Obtain Comparator', '"id": "minecraft:comparator"', 1],
    "I0010": ['Craft a Pot with 4 Sherds', '"id": "minecraft:decorated_pot"', 2],
    "I0011": ['Obtain Diamond Tools', '"id": "minecraft:diamond_pickaxe"', 1],
    "I0012": ['Obtain Dragon Egg', '"id": "minecraft:dragon_egg"', 4],
    "I0013": ['Obtain End Crystal', '"id": "minecraft:end_crystal"', 3],
    "I0014": ['Obtain End Rod', '"id": "minecraft:end_rod"', 4],
    "I0015": ['Obtain Ender Chest', '"id": "minecraft:ender_chest"', 3],
    "I0016": ['Obtain Froglight', '"id": "minecraft:pearlescent_froglight"', 3],
    "I0017": ['Obtain Gold Tools', '"id": "minecraft:golden_pickaxe"', 1],
    "I0018": ['Obtain Grass Block', '"id": "minecraft:grass_block"', 2],
    "I0019": ['Brew Healing Potion', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:healing"}}', 3],
    "I0020": ['Obtain Honey Bottle', '"id": "minecraft:honey_bottle"', 2],
    "I0021": ['Obtain Full Iron Armor', '"id": "minecraft:iron_chestplate"', 1],
    "I0022": ['Obtain Full Leather Armor', '"id": "minecraft:leather_chestplate"', 1],
    "I0023": ['Obtain Mossy Stone Brick Wall', '"id": "minecraft:mossy_stone_brick_wall"', 1],
    "I0024": ['Obtain Mushroom Stem', '"id": "minecraft:mushroom_stem"', 2],
    "I0025": ['Obtain Netherite Armor', '"id": "minecraft:netherite_helmet"', 3],
    "I0026": ['Obtain Powder Snow Bucket', '"id": "minecraft:powder_snow_bucket"', 1],
    "I0027": ['Obtain All Raw Ore Blocks', '"id": "minecraft:raw_iron_block"', 1],
    "I0028": ['Obtain Red Nether Brick Stairs', '"id": "minecraft:red_nether_brick_stairs"', 2],
    "I0029": ['Obtain Scaffolding', '"id": "minecraft:scaffolding"', 1],
    "I0030": ['Obtain Soul Lantern', '"id": "minecraft:soul_lantern"', 1],
    "I0031": ['Obtain Stone Tools', '"id": "minecraft:stone_pickaxe"', 1],
    "I0032": ['Brew Swiftness Potion', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:swiftness"}}', 3],
    "I0033": ['Obtain Bucket of Tropical Fish', '"id": "minecraft:tropical_fish_bucket"', 1],
    "I0034": ['Obtain Wither Skeleton Skull', '"id": "minecraft:wither_skeleton_skull"', 3],
    "I0035": ['Obtain All Colors of Wool', '"id": "minecraft:white_wool"', 2],
    "I0036": ['Obtain All Log Types', '"id": "minecraft:oak_log"', 3],
    "I0037": ['Obtain Trident', '"id": "minecraft:trident"', 3],
    "I0038": ['Obtain Nautilus Shell', '"id": "minecraft:nautilus_shell"', 3],
    "I0039": ['Obtain Brush', '"id": "minecraft:brush"', 1],
    "I0040": ['Obtain Banner Pattern', '"id": "minecraft:creeper_banner_pattern"', 1],
    "I0041": ['Obtain All Banner Patterns', '"id": "minecraft:creeper_banner_pattern"', 4],
    "I0042": ['Obtain Trail Ruins Armor Trim', '"id": "minecraft:wayfinder_armor_trim_smithing_template"', 3],
    "I0043": ['Use 4 Unique Armor Trims', '"id": "minecraft:rib_armor_trim_smithing_template"', 2],
    "I0044": ['Use 6 Unique Armor Trims', '"id": "minecraft:snout_armor_trim_smithing_template"', 3],
    "I0045": ['Obtain Recovery Compass', '"id": "minecraft:recovery_compass"', 3],
    "I0046": ['Obtain All Swords', '"id": "minecraft:netherite_sword"', 3],
    "I0047": ['Obtain All Shovels', '"id": "minecraft:netherite_shovel"', 3],
    "I0048": ['Obtain All Axes', '"id": "minecraft:netherite_axe"', 3],
    "I0049": ['Obtain Full Diamond Armor', '"id": "minecraft:diamond_chestplate"', 2],
    "I0050": ['Obtain Full Gold Armor', '"id": "minecraft:golden_chestplate"', 1],
    "I0051": ['Obtain Rabbit Foot', '"id": "minecraft:rabbit_foot"', 2],
    "I0052": ['Obtain Totem of Undying', '"id": "minecraft:totem_of_undying"', 3],
    "I0053": ['Obtain Name Tag', '"id": "minecraft:name_tag"', 2],
    "I0054": ['Obtain Written Book', '"id": "minecraft:written_book"', 1],
    "I0055": ['Obtain Bookshelf', '"id": "minecraft:bookshelf"', 1],
    "I0056": ['Obtain Wolf Armor', '"id": "minecraft:wolf_armor"', 2],
    "I0057": ['Get All Overworld Ore Blocks', '"id": "minecraft:diamond_block"', 3, 'Requirements: Coal, Iron, Copper, Gold, Lapis, Redstone, Emerald and Diamond blocks'],
    "I0058": ['Obtain Full Iron Tools', '"id": "minecraft:iron_pickaxe"', 1],
    "I0059": ['Obtain Sea Lantern', '"id": "minecraft:sea_lantern"', 1],
    "I0060": ['Obtain Flowering Azalea', '"id": "minecraft:flowering_azalea"', 1],
    "I0061": ['Obtain Bell', '"id": "minecraft:bell"', 1],
    "I0062": ['Obtain Ancient Debris', '"id": "minecraft:ancient_debris"', 2],
    "I0063": ['Obtain Heart of the Sea', '"id": "minecraft:heart_of_the_sea"', 1],
    "I0064": ['Obtain Lodestone', '"id": "minecraft:lodestone"', 3],
    "I0065": ['Obtain Sponge', '"id": "minecraft:sponge"', 2],
    "I0066": ['Obtain TNT', '"id": "minecraft:tnt"', 1],
    "I0067": ['Obtain Goat Horn', '"id": "minecraft:goat_horn"', 2],
    "I0068": ['Obtain Mud Brick Wall', '"id": "minecraft:mud_brick_wall"', 1],
    "I0069": ['Obtain Daylight Detector', '"id": "minecraft:daylight_detector"', 2],
    "I0070": ['Obtain Redstone Repeater', '"id": "minecraft:repeater"', 1],
    "I0071": ['Obtain Observer', '"id": "minecraft:observer"', 1],
    "I0072": ['Obtain Piston', '"id": "minecraft:piston"', 1],
    "I0073": ['Obtain Sticky Piston', '"id": "minecraft:sticky_piston"', 2],
    "I0074": ['Obtain Every Horse Armor', '"id": "minecraft:diamond_horse_armor"', 3],
    "I0075": ['Obtain Every Type of Seed', '"id": "minecraft:wheat_seeds"', 2],
    "I0076": ['Obtain 64 Magenta Concrete', '"id": "minecraft:magenta_concrete"', 1],
    "I0077": ['Obtain 64 Red Concrete', '"id": "minecraft:red_concrete"', 1],
    "I0078": ['Obtain 64 Orange Concrete', '"id": "minecraft:orange_concrete"', 1],
    "I0079": ['Obtain 64 Yellow Concrete', '"id": "minecraft:yellow_concrete"', 1],
    "I0080": ['Obtain 64 Lime Concrete', '"id": "minecraft:lime_concrete"', 2],
    "I0081": ['Obtain 64 Green Concrete', '"id": "minecraft:green_concrete"', 2],
    "I0082": ['Obtain 64 Light Blue Concrete', '"id": "minecraft:light_blue_concrete"', 1],
    "I0083": ['Obtain 64 Cyan Concrete', '"id": "minecraft:cyan_concrete"', 2],
    "I0084": ['Obtain 64 Blue Concrete', '"id": "minecraft:blue_concrete"', 1],
    "I0085": ['Obtain 64 Purple Concrete', '"id": "minecraft:purple_concrete"', 1],
    "I0086": ['Obtain 64 Black Concrete', '"id": "minecraft:black_concrete"', 1],
    "I0087": ['Brew Invisibility Potion', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:invisibility"}}', 3],
    "I0088": ['Brew Jump Boost Potion', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:leaping"}}', 3],
    "I0089": ['Obtain Tinted Glass', '"id": "minecraft:tinted_glass"', 2],
    "I0090": ['Obtain All Furnace Variants', '"id": "minecraft:furnace"', 1],
    "I0091": ['Obtain Sniffer Egg', '"id": "minecraft:sniffer_egg"', 2],
    "I0092": ['Obtain Pink Glazed Terracotta', '"id": "minecraft:pink_glazed_terracotta"', 1],
    "I0093": ['Obtain Magenta Glazed Terracotta', '"id": "minecraft:magenta_glazed_terracotta"', 1],
    "I0094": ['Obtain Red Glazed Terracotta', '"id": "minecraft:red_glazed_terracotta"', 1],
    "I0095": ['Obtain Orange Glazed Terracotta', '"id": "minecraft:orange_glazed_terracotta"', 1],
    "I0096": ['Obtain Yellow Glazed Terracotta', '"id": "minecraft:yellow_glazed_terracotta"', 1],
    "I0097": ['Obtain Lime Glazed Terracotta', '"id": "minecraft:lime_glazed_terracotta"', 2],
    "I0098": ['Obtain Green Glazed Terracotta', '"id": "minecraft:green_glazed_terracotta"', 2],
    "I0099": ['Obtain Cyan Glazed Terracotta', '"id": "minecraft:cyan_glazed_terracotta"', 2],
    "I0100": ['Obtain Light Blue Glazed Terracotta', '"id": "minecraft:light_blue_glazed_terracotta"', 1],
    "I0101": ['Obtain Blue Glazed Terracotta', '"id": "minecraft:blue_glazed_terracotta"', 1],
    "I0102": ['Obtain Purple Glazed Terracotta', '"id": "minecraft:purple_glazed_terracotta"', 1],
    "I0103": ['Obtain Black Glazed Terracotta', '"id": "minecraft:black_glazed_terracotta"', 1],
    "I0104": ['Obtain Nether Star', '"id": "minecraft:nether_star"', 4],
    "I0105": ['Obtain Netherite Ingot', '"id": "minecraft:netherite_ingot"', 3],
    "I0106": ['Obtain Glow Item Frame', '"id": "minecraft:glow_item_frame"', 2],
    "I0107": ['Obtain Mace', '"id": "minecraft:mace"', 4],
    "I0108": ['Obtain Block of Dried Kelp', '"id": "minecraft:dried_kelp_block"', 2],
    "I0109": ['Obtain Elytra', '"id": "minecraft:elytra"', 4],
    "I0110": ['Obtain Turtle Scute', '"id": "minecraft:turtle_scute"', 3],
    "I0111": ['Obtain Pink Candle', '"id": "minecraft:pink_candle"', 1],
    "I0112": ['Obtain Magenta Candle', '"id": "minecraft:magenta_candle"', 1],
    "I0113": ['Obtain Red Candle', '"id": "minecraft:red_candle"', 1],
    "I0114": ['Obtain Orange Candle', '"id": "minecraft:orange_candle"', 1],
    "I0115": ['Obtain Yellow Candle', '"id": "minecraft:yellow_candle"', 1],
    "I0116": ['Obtain Lime Candle', '"id": "minecraft:lime_candle"', 2],
    "I0117": ['Obtain Green Candle', '"id": "minecraft:green_candle"', 2],
    "I0118": ['Obtain Cyan Candle', '"id": "minecraft:cyan_candle"', 2],
    "I0119": ['Obtain Light Blue Candle', '"id": "minecraft:light_blue_candle"', 1],
    "I0120": ['Obtain Blue Candle', '"id": "minecraft:blue_candle"', 1],
    "I0121": ['Obtain Purple Candle', '"id": "minecraft:purple_candle"', 1],
    "I0122": ['Obtain Black Candle', '"id": "minecraft:black_candle"', 1],
    "I0123": ['Obtain Honey Block', '"id": "minecraft:honey_block"', 2],
    "I0124": ['Obtain Glow Lichen', '"id": "minecraft:glow_lichen"', 2],
    "I0125": ['Obtain Flower Pot', '"id": "minecraft:flower_pot"', 1],
    "I0126": ['Obtain All Minecart Types', '"id": "minecraft:minecart"', 2],
    "I0127": ['Obtain Iron Bars', '"id": "minecraft:iron_bars"', 1],
    "I0128": ['Obtain Music Disc 5', '"id": "minecraft:music_disc_5"', 3],
    "I0129": ['Obtain Music Disc 11', '"id": "minecraft:music_disc_11"', 3],
    "I0130": ['Obtain Music Disc 13', '"id": "minecraft:music_disc_13"', 2],
    "I0131": ['Obtain Music Disc Blocks', '"id": "minecraft:music_disc_blocks"', 3],
    "I0132": ['Obtain Music Disc Cat', '"id": "minecraft:music_disc_cat"', 2],
    "I0133": ['Obtain Music Disc Chirp', '"id": "minecraft:music_disc_chirp"', 3],
    "I0134": ['Obtain Music Disc Creator', '"id": "minecraft:music_disc_creator"', 4],
    "I0135": ['Obtain Creator Music Box', '"id": "minecraft:music_disc_creator_music_box"', 3],
    "I0136": ['Obtain Music Disc Far', '"id": "minecraft:music_disc_far"', 3],
    "I0137": ['Obtain Music Disc Mall', '"id": "minecraft:music_disc_mall"', 3],
    "I0138": ['Obtain Music Disc Mellohi', '"id": "minecraft:music_disc_mellohi"', 3],
    "I0139": ['Obtain Music Disc Otherside', '"id": "minecraft:music_disc_otherside"', 3],
    "I0140": ['Obtain Music Disc Pigstep', '"id": "minecraft:music_disc_pigstep"', 4],
    "I0141": ['Obtain Music Disc Precipice', '"id": "minecraft:music_disc_precipice"', 3],
    "I0142": ['Obtain Music Disc Relic', '"id": "minecraft:music_disc_relic"', 4],
    "I0143": ['Obtain Music Disc Stal', '"id": "minecraft:music_disc_stal"', 3],
    "I0144": ['Obtain Music Disc Strad', '"id": "minecraft:music_disc_strad"', 3],
    "I0145": ['Obtain Music Disc Wait', '"id": "minecraft:music_disc_wait"', 3],
    "I0146": ['Obtain Music Disc Ward', '"id": "minecraft:music_disc_ward"', 3],

    # EAT GOALS
    "E0001": ['Eat Chorus Fruit', '"id": "minecraft:chorus_fruit"', 4],
    "E0002": ['Eat Poisonous Potato', '"id": "minecraft:poisonous_potato"', 1],
    "E0003": ['Eat Pumpkin Pie', '"id": "minecraft:pumpkin_pie"', 1],
    "E0004": ['Eat Rabbit Stew', '"id": "minecraft:rabbit_stew"', 1],
    "E0005": ['Eat Enchanted Golden Apple', '"id": "minecraft:enchanted_golden_apple"', 2],
    "E0006": ['Eat Spider Eye', '"id": "minecraft:spider_eye"', 1],
    "E0007": ['Eat Beetroot', '"id": "minecraft:beetroot"', 1],
    "E0008": ['Eat 10 Unique Foods', '"id": "minecraft:apple","components": {"minecraft:custom_model_data": 505063}', 1],
    "E0009": ['Eat 20 Unique Foods', '"id": "minecraft:apple","components": {"minecraft:custom_model_data": 505063}', 2],
    "E0010": ['Eat Suspicious Stew', '"id": "minecraft:suspicious_stew"', 1],
    "E0011": ['Eat a Glow Berry', '"id": "minecraft:glow_berries"', 1],
    "E0012": ['Eat a Cookie', '"id": "minecraft:cookie"', 1],
    "E0013": ['Eat an Apple', '"id": "minecraft:apple"', 1],
    "E0014": ['Eat a Carrot', '"id": "minecraft:carrot"', 1],
    "E0015": ['Eat Dried Kelp', '"id": "minecraft:dried_kelp"', 1],
    # "E0016": ['Eat All Harmful Foods', '"id": "minecraft:rotten_flesh"', 2], #rotten flesh, spider eye, poisonous potato, raw chicken, pufferfish
    # "E0017": ['Eat All Raw Seafood', '"id": "minecraft:salmon"', 2], #cod, salmon, pufferfish, tropical fish

    # ADVANCEMENT GOALS
    "A0001": ['Get 25 Unique Advancements', '"id": "minecraft:experience_bottle","components": {"minecraft:custom_model_data": 2}', 2],
    "A0002": ['Get Bullseye Advancement', '"id": "minecraft:target"', 1],
    "A0003": ['Cure Zombie Villager', '"id": "minecraft:golden_apple"', 3],
    "A0004": ['Use Enchantment Table', '"id": "minecraft:enchanting_table"', 2],
    "A0005": ['Get Oh Shiny Advancement', '"id": "minecraft:gold_ingot"', 1],
    "A0006": ['Open Ominous Vault', '"id": "minecraft:ominous_trial_key"', 2],
    "A0007": ['Get Sniper Duel Advancement', '"id": "minecraft:bow"', 1],
    "A0008": ['Do any Spyglass Advancement', '"id": "minecraft:spyglass"', 1],
    "A0009": ['Do Star Trader Advancement', '"id": "minecraft:emerald_block"', 2],
    "A0010": ['Ride Strider', '"id": "minecraft:warped_fungus_on_a_stick"', 2],
    "A0011": ['Trade with a Villager', '"id": "minecraft:emerald"', 1],
    "A0012": ['Open Trial Vault', '"id": "minecraft:trial_key"', 1],
    "A0013": ['Apply Armor Trim', '"id": "minecraft:coast_armor_trim_smithing_template"', 1],
    "A0014": ['Obtain all Froglights', '"id": "minecraft:verdant_froglight"', 4],
    "A0015": ['Get Subspace Bubble Advancement', '"id": "minecraft:obsidian"', 2],
    "A0016": ['Tame Every Cat Variant', '"id": "minecraft:cod"', 3],
    "A0017": ['Fully Charge Respawn Anchor', '"id": "minecraft:respawn_anchor"', 2],
    "A0018": ['Do Power of Books Advancement', '"id": "minecraft:chiseled_bookshelf"', 2],
    "A0019": ['Do Caves and Cliffs Advancement', '"id": "minecraft:water_bucket"', 3],
    "A0020": ['Summon Iron Golem', '"id": "minecraft:carved_pumpkin"', 2],
    "A0021": ['Get 15 Unique Advancements', '"id": "minecraft:experience_bottle","components": {"minecraft:custom_model_data": 3}', 1],
    "A0022": ['Get 35 Unique Advancements', '"id": "minecraft:experience_bottle","components": {"minecraft:custom_model_data": 4}', 3],

    # MISC GOALS
    "X0001": ['Get 30 Levels', '"id": "minecraft:experience_bottle","components": {"minecraft:custom_model_data": 1}', 2],
    "X0002": ['Get 64 of the Same Item', '"id": "minecraft:dirt"', 1],
    "X0003": ['Get Absorption', '"id": "minecraft:golden_apple"', 1],
    "X0004": ['Get Glowing', '"id": "minecraft:spectral_arrow","components": {"minecraft:custom_model_data": 1}', 1],
    "X0005": ['Get Poisoned', '"id": "minecraft:spider_eye","components": {"minecraft:custom_model_data": 1}', 1],
    "X0006": ['Use a Jukebox', '"id": "minecraft:jukebox"', 1],
    "X0007": ['Mine Diamond', '"id": "minecraft:diamond_ore"', 1],
    "X0008": ['Mine Mob Spawner', '"id": "minecraft:spawner"', 1],
    "X0009": ['Sprint 1km', '"id": "minecraft:diamond_boots"', 1],
    "X0010": ['Start a Raid', '"id": "minecraft:ominous_bottle"', 2],
    # "X0011": ['Fill Inventory with Unique Items', '"id": "minecraft:chest"', 1],
    "X0012": ['Mine Emerald Ore', '"id": "minecraft:emerald_ore"', 2],
    # "X0013": ['Get a Villager to Max Level', '"id": "minecraft:emerald"', 3],
    "X0014": ['Wear a Pumpkin for 5 Minutes', '"id": "minecraft:carved_pumpkin"', 2],
    "X0015": ['Have 3 Status Effects at Once', '"id": "minecraft:milk_bucket"', 1],
    "X0016": ['Have 6 Status Effects at Once', '"id": "minecraft:milk_bucket"', 2],
    "X0017": ['Get Nausea', '"id": "minecraft:pufferfish"', 1],
    "X0018": ['Take 200 Damage', '"id": "minecraft:wooden_sword"', 1],
    "X0019": ['Get Leaping', '"id": "minecraft:rabbit_foot"', 1],
    "X0020": ['Empty Hunger Bar', '"id": "minecraft:rotten_flesh"', 1],
    "X0021": ['Wash Leather Armor', '"id": "minecraft:leather_chestplate"', 1],
    # "X0022": ['Use Banner Pattern on Banner', '"id": "minecraft:flow_banner_pattern"', 1],
    "X0023": ['Have 9 Status Effects at Once', '"id": "minecraft:milk_bucket"', 3],
    "X0024": ['Have 12 Status Effects at Once', '"id": "minecraft:milk_bucket"', 3],
    "X0025": ['Get 15 Levels', '"id": "minecraft:experience_bottle","components": {"minecraft:custom_model_data": 2}', 2],
    "X0026": ['Get Withered', '"id": "minecraft:wither_rose"', 2],
    "X0027": ['Get Mining Fatigue', '"id": "minecraft:wooden_pickaxe"', 2],
    "X0028": ['Get Blindness', '"id": "minecraft:suspicious_stew"', 2],
    "X0029": ['Get Strength', '"id": "minecraft:blaze_powder"', 2],
    "X0030": ['Get Fire Resistance', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:fire_resistance"}}', 2],
    "X0031": ['Get Water Breathing', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:water_breathing"}}', 2],
    "X0032": ['Get Night Vision', '"id": "minecraft:potion","components": {"minecraft:potion_contents": {"potion": "minecraft:night_vision"}}', 2],

    # LOCATION GOALS
    "L0001": ['Find an Ancient City', '"id": "minecraft:sculk_shrieker"', 2],
    "L0002": ['Reach Bedrock', '"id": "minecraft:bedrock"', 1],
    "L0003": ['Reach Height Limit', '"id": "minecraft:glass"', 1],
    "L0004": ['Enter Nether Fortress', '"id": "minecraft:nether_bricks"', 1],
    "L0005": ['Enter Bastion', '"id": "minecraft:gilded_blackstone"', 1],
    "L0006": ['Enter End City', '"id": "minecraft:purpur_pillar"', 4],
    "L0007": ['Enter End', '"id": "minecraft:end_portal_frame"', 3],
    "L0008": ['Locate all Nether Biomes', '"id": "minecraft:netherite_boots"', 3],
    "L0009": ['Enter Nether', '"id": "minecraft:netherrack"', 1],
    "L0010": ['Locate Stronghold', '"id": "minecraft:ender_eye"', 3],
    "L0011": ['Locate Trail Ruins', '"id": "minecraft:brush"', 3],
    "L0012": ['Travel to Nether Roof', '"id": "minecraft:bedrock"', 2],
    "L0013": ['Locate Woodland Mansion', '"id": "minecraft:red_carpet"', 4],

}

exclusiveSets = {
    # When exclusive sets are enabled (default), two goals in the same set will *almost* never show up on the same board.
    'sheep': ['K0003', 'K0005', 'K0010', 'K0013', 'K0014', 'K0015', 'K0016', 'K0017', 'K0019', 'K0020', 'K0029'],
    'poison': ['X0005', 'E0006'],
    'netherite': ['I0002', 'I0003', 'I0025', 'I0046', 'I0047', 'I0048', 'I0105'],
    'opponent': ['N0001', 'N0002', 'N0003', 'N0004', 'N0005', 'N0006', 'N0007', 'N0008', 'N0009', 'N0010', 'N0011'],
    'redstone': ['I0009', 'I0069', 'I0070', 'I0071'],
    'piston': ['I0072', 'I0073'],
    'concrete': ['I0076', 'I0077', 'I0078', 'I0079', 'I0080', 'I0081', 'I0082', 'I0083', 'I0084', 'I0085', 'I0086'],
    'brewing': ['I0088', 'I0087', 'I0032', 'I0019'],
    'seeds': ['N0007', 'B0001', 'I0075'],
    'obsidian': ['N0006', 'A0004'],
    'terracotta': ['I0092', 'I0093', 'I0094', 'I0095', 'I0096', 'I0097', 'I0098', 'I0099', 'I0100', 'I0101', 'I0102', 'I0103'],
    'candle': ['I0111', 'I0112', 'I0113', 'I0114', 'I0115', 'I0116', 'I0117', 'I0118', 'I0119', 'I0120', 'I0121', 'I0122'],
    'effects': ['X0003', 'X0004', 'X0005', 'X0017', 'X0019', 'X0026', 'X0027', 'X0028', 'X0029', 'X0030', 'X0031', 'X0032'],
    'musicdisc': ['I0128', 'I0129', 'I0130', 'I0131', 'I0132', 'I0133', 'I0134', 'I0135', 'I0136', 'I0137', 'I0138', 'I0139', 'I0140', 'I0141', 'I0142', 'I0143', 'I0144', 'I0145', 'I0146']
}

unique_advancements = ['A0001', 'A0021', 'A0022']

index_length = len(goalDictionary)
# for i in goalDictionary:
#   print(f'{i}: {goalDictionary[i][0]}')
print("Index Version:", index_version, " Goals:", index_length)
