import random
import json

def load_option(key, default=None):
    with open('./options.txt', 'r') as f:
        for line in f.readlines():
            if line.startswith('#'): continue
            elif '=' not in line: continue
            else:
                keyval = line.split('=')
                if len(keyval) != 2: continue
                if keyval[0] == key: 
                    val = keyval[1].strip('\n')
                    if val.isdigit(): return int(val)
                    if val.lower() == "false": return False
                    if val.lower() == "true": return True
                    return val
        return default

# Set Environment Variables
VERSION = '2.4.0'
MCVERSION = '1.21.8-26.3'
OUTPUT_DIR = load_option('OUTPUT_DIR', default='Downloads')
DEFAULT_MODE = load_option('DEFAULT_MODE', default='Lockout')
DEFAULT_SIZE = load_option('DEFAULT_SIZE', default=5)
DEFAULT_DIFFICULTY = load_option('DEFAULT_DIFFICULTY', default='1-5')
DEBUG = load_option('DEBUG', default=False)

LK_START_TIME=load_option('LK_START_TIME', default=45)
LK_MAX_TIME=load_option('LK_MAX_TIME', default=120)
LK_SHOW_PROGRESS=load_option('LK_SHOW_PROGRESS', default=True)
LK_ALLOW_PVP=load_option('LK_ALLOW_PVP', default=True)
LK_ALLOW_FRIENDLY_FIRE=load_option('LK_ALLOW_FRIENDLY_FIRE', default=True)
LK_ALLOW_TRACKER=load_option('LK_ALLOW_TRACKER', default=True)
LK_ALLOW_DRAW=load_option('LK_ALLOW_DRAW', default=True)
LK_ALLOW_RESIGN=load_option('LK_ALLOW_RESIGN', default=True)
LK_END_ON_WIN=load_option('LK_END_ON_WIN', default=True)
LK_SHOW_TIMER=load_option('LK_SHOW_TIMER', default=True)


GOAL_INDEX = {
        # id: [name, icon, customModelDataBool, difficulty, java_id]
        # Commented goals are not yet implemented or are broken

        "A0001" : ['Get 15 Unique Advancements', 'experience_bottle', True, 2, 'GET_15_ADVANCEMENTS'],
        "A0002" : ['Get 25 Unique Advancements', 'experience_bottle', True, 4, 'GET_25_ADVANCEMENTS'],
        "A0003" : ['Get 35 Unique Advancements', 'experience_bottle', True, 6, 'GET_35_ADVANCEMENTS'],
        "A0004" : ['Get Bullseye Advancement', 'target', False, 3, 'GET_BULLSEYE_ADVANCEMENT'],
        "A0005" : ['Cure Zombie Villager', 'golden_apple', False, 3, 'GET_ZOMBIE_DOCTOR_ADVANCEMENT'],
        "A0006" : ['Use Enchantment Table', 'enchanting_table', False, 3, 'USE_ENCHANTING_TABLE'],
        "A0007" : ['Get Oh Shiny Advancement', 'gold_ingot', False, 2, 'GET_OH_SHINY_ADVANCEMENT'],
        "A0008" : ['Get Sniper Duel Advancement', 'bow', False, 3, 'GET_SNIPER_DUEL_ADVANCEMENT'],
        "A0009" : ['Do any Spyglass Advancement', 'spyglass', False, 2, 'GET_ANY_SPYGLASS_ADVANCEMENT'],
        "A0010" : ['Do Star Trader Advancement', 'emerald_block', False, 6, ''],
        "A0011" : ['Ride Strider', 'warped_fungus_on_a_stick', False, 3, 'GET_THIS_BOAT_HAS_LEGS_ADVANCEMENT'],
        "A0012" : ['Trade with a Villager', 'emerald', False, 2, 'GET_WHAT_A_DEAL_ADVANCEMENT'],
        "A0013" : ['Get Subspace Bubble Advancement', 'obsidian', False, 5, ''],
        "A0014" : ['Fully Charge Respawn Anchor', 'respawn_anchor', False, 4, 'GET_NOT_QUITE_NINE_LIVES_ADVANCEMENT'],
        "A0015" : ['Do Power of Books Advancement', 'chiseled_bookshelf', False, 3, ''],
        "A0016" : ['Do Caves and Cliffs Advancement', 'water_bucket', False, 6, ''],
        "A0017" : ['Summon Iron Golem', 'carved_pumpkin', False, 4, 'GET_HIRED_HELP_ADVANCEMENT'],
        "A0018" : ['Start a Raid', 'ominous_bottle', False, 6, ''],
        "A0019" : ['Locate all Nether Biomes', 'netherite_boots', False, 5, 'GET_HOT_TOURIST_DESTINATIONS_ADVANCEMENT'],
        "A0020" : ['Enter Nether Fortress', 'nether_bricks', False, 3, 'GET_A_TERRIBLE_FORTRESS_ADVANCEMENT'],
        "A0021" : ['Enter Bastion', 'gilded_blackstone', False, 3, 'GET_THOSE_WERE_THE_DAYS_ADVANCEMENT'],
        "A0022" : ['Enter End City', 'purpur_pillar', False, 9, 'GET_THE_CITY_AT_THE_END_OF_THE_GAME_ADVANCEMENT'],
        "A0023" : ['Enter End', 'end_portal_frame', False, 7, 'ENTER_END'],
        "A0024" : ['Enter Nether', 'flint_and_steel', True, 2, 'ENTER_NETHER'],
        "A0025" : ['Locate Stronghold', 'ender_eye', False, 6, 'GET_EYE_SPY_ADVANCEMENT'],
        "A0026" : ['Apply Armor Trim', 'coast_armor_trim_smithing_template', True, 2, ''],
        "A0027" : ['Open Trial Vault', 'trial_key', False, 1, 'OPEN_TRIAL_VAULT'],
        "A0028" : ['Repair Wolf Armor', 'wolf_armor', False, 2, ''],
        "A0029" : ['Open Ominous Vault', 'ominous_trial_key', False, 2, ''],
        "A0031" : ['Craft a Crafter in a Crafter', 'crafter', False, 3, ''],
        "A0032" : ['Hydrate a Dried Ghast', '', False, 4, 'GET_STAY_HYDRATED_ADVANCEMENT'],
        "A0033" : ['Get "Wax On" Advancement', '', False, 2, 'GET_WAX_ON_ADVANCEMENT'],
        "A0034" : ['Get "Wax Off" Advancement', '', False, 2, 'GET_WAX_OFF_ADVANCEMENT'],
        "A0035" : ['Use Compass on a Lodestone', '', False, 3, 'GET_COUNTRY_LODE_TAKE_ME_HOME_ADVANCEMENT'],
        "A0036" : ['Get "Mob Kabob" Advancement', '', False, 1, 'SKEWER_MOBS'],
        "A0037" : ['Get "Heart Transplanter" Achivement', '', False, 5, 'GET_HEART_TRANSPLANTER_ADVANCEMENT'],
        "A0038" : ['Enter Trial Chamber', '', False, 2, 'ENTER_A_TRIAL_CHAMBER'],
        "A0039" : ['Equip Wolf Armor', '', False, 4, 'PUT_WOLF_ARMOR_ON_WOLF'],
        "A0040" : ['Get 10 Unique Advancements', 'experience_bottle', False, 1, 'GET_10_ADVANCEMENTS'],
        "A0041" : ['Get 20 Unqiue Advancements', 'experience_bottle', False, 3, 'GET_20_ADVANCEMENTS'],
        "A0042" : ['Get 30 Unqiue Advancements', 'experience_bottle', False, 5, 'GET_30_ADVANCEMENTS'],
        "B0001" : ['Breed Axolotl', 'tropical_fish_bucket', True, 4, 'BREED_AXOLOTL'],
        "B0002" : ['Breed Cat', 'cod', True, 3, 'BREED_CAT'],
        "B0003" : ['Breed Chicken', 'wheat_seeds', True, 1, 'BREED_CHICKEN'],
        "B0004" : ['Breed Cow', 'wheat', True, 2, 'BREED_COW'],
        "B0005" : ['Breed Fox', 'sweet_berries', True, 4, 'BREED_FOX'],
        "B0006" : ['Breed Goat', 'wheat', True, 3, 'BREED_GOAT'],
        "B0007" : ['Breed Hoglin', 'crimson_fungus', True, 3, 'BREED_HOGLIN'],
        "B0008" : ['Breed Horse', 'golden_carrot', True, 2, 'BREED_HORSE'],
        "B0009" : ['Breed Mooshroom', 'red_mushroom', True, 6, ''],
        "B0010" : ['Breed Ocelot', 'cod', True, 6, ''],
        "B0011" : ['Breed Panda', 'bamboo', True, 5, ''],
        "B0012" : ['Breed Pig', 'potato', True, 2, 'BREED_PIG'],
        "B0013" : ['Breed Rabbit', 'carrot', True, 3, 'BREED_RABBIT'],
        "B0014" : ['Breed Sheep', 'wheat', True, 1, 'BREED_SHEEP'],
        "B0015" : ['Breed Strider', 'warped_fungus', True, 3, 'BREED_STRIDER'],
        "B0016" : ['Breed Turtle', 'seagrass', True, 3, 'BREED_TURTLE'],
        "B0017" : ['Breed Wolf', 'bone', True, 3, 'BREED_WOLF'],
        "B0018" : ['Breed 4 Unique Mobs', 'wheat', True, 2, 'BREED_4_UNIQUE_ANIMALS'],
        "B0019" : ['Breed 6 Unique Mobs', 'wheat', True, 3, 'BREED_6_UNIQUE_ANIMALS'],
        "B0020" : ['Breed 8 Unique Mobs', 'wheat', True, 4, 'BREED_8_UNIQUE_ANIMALS'],
        "B0021" : ['Breed 12 Unique Mobs', 'wheat', True, 7, ''],
        "B0022" : ['Breed Frog', 'slime_ball', True, 4, 'BREED_FROGS'],
        "B0023" : ['Breed Sniffer', 'sniffer_egg', True, 9, ''],
        "B0024" : ['Breed Armadillo', 'spider_eye', True, 4, 'BREED_ARMADILLO'],
        "B0025" : ['Breed Camel', 'cactus', False, 4, 'BREED_CAMEL'],
        "D0001" : ['Die to Bee', 'beehive', True, 1, 'DIE_BY_BEE_STING'],
        "D0002" : ['Die to Llama', 'hay_block', True, 3, ''],
        "D0003" : ['Die to Iron Golem', 'carved_pumpkin', True, 2, 'DIE_BY_IRON_GOLEM'],
        "D0004" : ['Die to Witch', 'glass_bottle', True, 2, ''],
        "D0005" : ['Die to Piglin Brute', 'golden_axe', True, 3, ''],
        "D0006" : ['Die on Pointed Dripstone', 'pointed_dripstone', True, 2, ''],
        "D0007" : ['Die to Polar Bear', 'cod', True, 3, 'DIE_TO_POLAR_BEAR'],
        "D0008" : ['Die to Warden', 'sculk_shrieker', True, 3, ''],
        "D0009" : ['Die to Creaking', 'creaking_heart', True, 5, ''],
        "D0010" : ['Die in Sweet Berry Bush', 'sweet_berries', True, 3, 'DIE_BY_BERRY_BUSH'],
        "D0011" : ['Die to Cactus', '', False, 1, 'DIE_BY_CACTUS'],
        "D0012" : ['Die by Falling off Vine', '', False, 2, 'DIE_BY_FALLING_OFF_VINE'],
        "D0013" : ['Die by Falling Stalactite', '', False, 3, 'DIE_BY_FALLING_STALACTITE'],
        "D0014" : ['Die to Firework', '', False, 2, 'DIE_BY_FIREWORK'],
        "D0015" : ['Die to Intentional Game Design', '', False, 3, 'DIE_BY_INTENTIONAL_GAME_DESIGN'],
        "D0016" : ['Die to Anvil', '', False, 4, 'DIE_BY_ANVIL'],
        "D0017" : ['Die to Magic', '', False, 3, 'DIE_BY_MAGIC'],
        "D0018" : ['Die to TNT Minecart', '', False, 3, 'DIE_BY_TNT_MINECART'],
        "D0019" : ['Die to Drowning', '', False, 1, 'DIE_BY_DROWNING'],
        "D0020" : ['Die to Freezing', '', False, 1, 'FREEZE_TO_DEATH'],
        # "D0021" : ['Die to Void', '', False, 7, ''],
        "D0022" : ['Die to Pufferfish', 'pufferfish', False, 1, 'DIE_TO_PUFFERFISH'],
        "E0001" : ['Eat Apple', 'apple', False, 1, ''],
        "E0002" : ['Eat Beetroot', 'beetroot', False, 3, ''],
        "E0003" : ['Eat Carrot', 'carrot', False, 2, ''],
        "E0004" : ['Eat Cookie', 'cookie', False, 3, 'EAT_COOKIE'],
        "E0005" : ['Eat Dried Kelp', 'dried_kelp', False, 1, ''],
        "E0006" : ['Eat Glow Berry', 'glow_berries', False, 2, 'EAT_GLOW_BERRY'],
        "E0007" : ['Eat Poisonous Potato', 'poisonous_potato', False, 2, 'EAT_POISONOUS_POTATO'],
        "E0008" : ['Eat Pumpkin Pie', 'pumpkin_pie', False, 2, 'EAT_PUMPKIN_PIE'],
        "E0009" : ['Eat Rabbit Stew', 'rabbit_stew', False, 2, 'EAT_RABBIT_STEW'],
        "E0010" : ['Eat Suspicious Stew', 'suspicious_stew', False, 2, 'EAT_SUSPICIOUS_STEW'],
        "E0011" : ['Eat Beetroot Stew', 'beetroot_soup', False, 3, 'EAT_BEETROOT_SOUP'],
        "E0012" : ['Eat Chorus Fruit', 'chorus_fruit', False, 8, 'EAT_CHORUS_FRUIT'],
        "E0013" : ['Eat Enchanted Golden Apple', 'enchanted_golden_apple', False, 6, ''],
        "E0014" : ['Eat Spider Eye', 'spider_eye', False, 1, ''],
        "E0015" : ['Eat 5 Unique Foods', 'apple', True, 1, 'EAT_5_UNIQUE_FOOD'],
        "E0016" : ['Eat 10 Unique Foods', 'apple', True, 2, 'EAT_10_UNIQUE_FOOD'],
        "E0017" : ['Eat 20 Unique Foods', 'apple', True, 4, 'EAT_20_UNIQUE_FOOD'],
        "E0018" : ['Eat Cake', 'cake', False, 3, 'EAT_CAKE'],
        "E0019" : ['Eat 15 Unique Foods', 'apple', False, 3, 'EAT_15_UNIQUE_FOOD'],
        "E0020" : ['Eat 25 Unique Foods', 'apple', False, 5, 'EAT_25_UNIQUE_FOOD'],
        "E0021" : ['Drink Honey Bottle', 'honey_bottle', False, 3, 'DRINK_HONEY_BOTTLE'],
        "E0022" : ['Drink Water Bottle', '', False, 1, 'DRINK_WATER_BOTTLE'],
        "I0001" : ['Obtain All Swords', 'netherite_sword', True, 6, ''],
        "I0002" : ['Obtain All Axes', 'netherite_axe', True, 6, ''],
        "I0003" : ['Obtain All Pickaxes', 'netherite_pickaxe', True, 6, ''],
        "I0004" : ['Obtain All Shovels', 'netherite_shovel', True, 6, ''],
        "I0005" : ['Obtain All Hoes', 'netherite_hoe', True, 6, ''],
        "I0006" : ['Obtain Full Leather Armor', 'leather_chestplate', True, 2, 'WEAR_LEATHER_ARMOR'],
        "I0007" : ['Obtain Chainmail Armor', 'chainmail_helmet', False, 4, 'WEAR_CHAIN_ARMOR_PIECE'],
        "I0008" : ['Obtain Full Chainmail Armor', 'chainmail_chestplate', True, 7, ''],
        "I0009" : ['Obtain Full Iron Armor', 'iron_chestplate', True, 3, 'WEAR_IRON_ARMOR'],
        "I0010" : ['Obtain Full Gold Armor', 'golden_chestplate', True, 2, 'WEAR_GOLDEN_ARMOR'],
        "I0011" : ['Obtain Diamond Armor', 'diamond_helmet', False, 3, 'WEAR_DIAMOND_ARMOR_PIECE'],
        "I0012" : ['Obtain Full Diamond Armor', 'diamond_chestplate', True, 4, 'WEAR_DIAMOND_ARMOR'],
        "I0013" : ['Obtain Netherite Armor', 'netherite_helmet', False, 6, 'WEAR_NETHERITE_ARMOR_PIECE'],
        "I0014" : ['Obtain Full Netherite Armor', 'netherite_chestplate', True, 10, ''],
        "I0015" : ['Obtain All Wooden Tools', 'wooden_pickaxe', True, 1, 'OBTAIN_WOODEN_TOOLS'],
        "I0016" : ['Obtain All Stone Tools', 'stone_pickaxe', True, 1, 'OBTAIN_STONE_TOOLS'],
        "I0017" : ['Obtain All Iron Tools', 'iron_pickaxe', True, 2, 'OBTAIN_IRON_TOOLS'],
        "I0018" : ['Obtain All Gold Tools', 'golden_pickaxe', True, 2, 'OBTAIN_GOLDEN_TOOLS'],
        "I0019" : ['Obtain All Diamond Tools', 'diamond_pickaxe', True, 4, 'OBTAIN_DIAMOND_TOOLS'],
        "I0020" : ['Obtain All Netherite Tools', 'netherite_pickaxe', True, 10, ''],
        "I0021" : ['Obtain All Log Types', 'jungle_log', True, 8, ''],
        "I0022" : ['Obtain All Wool Blocks', 'white_wool', True, 5, ''],
        "I0023" : ['Obtain All Rail Types', 'powered_rail', True, 3, 'OBTAIN_ALL_RAIL_TYPES'],
        "I0024" : ['Obtain All Raw Ore Blocks', 'raw_iron_block', True, 2, 'OBTAIN_ALL_RAW_ORE_BLOCKS'],
        "I0025" : ['Obtain All Overworld Ores', 'redstone_ore', True, 8, ''],
        "I0026" : ['Obtain All Overworld Ore Blocks', 'diamond_block', True, 8, ''],
        "I0027" : ['Obtain All Nether Ores', 'nether_gold_ore', True, 6, ''],
        "I0028" : ['Obtain All Banner Patterns', 'creeper_banner_pattern', False, 10, ''],
        "I0029" : ['Obtain All Nether Ore Blocks', 'netherite_block', True, 10, ''],
        "I0030" : ['Obtain Every Horse Armor', 'diamond_horse_armor', True, 6, 'OBTAIN_4_UNIQUE_HORSE_ARMOR'],
        "I0031" : ['Obtain Every Type of Seed', 'wheat_seeds', True, 3, 'OBTAIN_4_UNIQUE_SEEDS'],
        "I0032" : ['Obtain All Minecart Types', 'minecart', True, 3, 'OBTAIN_ALL_MINECARTS'],
        "I0033" : ['Obtain All Furnace Variants', 'furnace', False, 1, 'OBTAIN_ALL_FURNACE_VARIANTS'],
        "I0034" : ['Obtain All Mushrooms', 'red_mushroom', False, 2, 'OBTAIN_ALL_MUSHROOMS'],
        "I0035" : ['Obtain All Pumpkin Types', 'pumpkin', False, 2, 'OBTAIN_ALL_PUMPKINS'],
        "I0036" : ['Obtain 5 Unique Saplings', 'oak_sapling', True, 2, ''],
        "I0037" : ['Obtain 6 Log Variants', 'acacia_log', False, 3, ''],
        "I0038" : ['Obtain 8 Log Variants', 'jungle_log', False, 6, ''],
        "I0039" : ['Obtain Cake', 'cake', False, 3, ''],
        "I0040" : ['Obtain Cobweb', 'cobweb', False, 3, 'OBTAIN_COBWEB'],
        "I0041" : ['Obtain Comparator', 'comparator', False, 3, 'OBTAIN_REDSTONE_COMPARATOR'],
        "I0042" : ['Obtain Repeater', 'repeater', False, 3, 'OBTAIN_REDSTONE_REPEATER'],
        "I0043" : ['Obtain Redstone Lamp', 'redstone_lamp', False, 3, 'OBTAIN_REDSTONE_LAMP'],
        "I0044" : ['Obtain End Crystal', 'end_crystal', False, 5, ''],
        "I0045" : ['Obtain End Rod', 'end_rod', False, 8, 'OBTAIN_END_ROD'],
        "I0046" : ['Obtain Ender Chest', 'ender_chest', False, 5, 'OBTAIN_ENDER_CHEST'],
        "I0047" : ['Obtain Grass Block', 'grass_block', False, 3, ''],
        "I0048" : ['Obtain Honey Bottle', 'honey_bottle', False, 3, ''],
        "I0049" : ['Obtain Honey Block', 'honey_block', False, 5, ''],
        "I0050" : ['Obtain Mossy Stone Brick Wall', 'mossy_stone_brick_wall', False, 2, 'OBTAIN_MOSSY_STONE_BRICK_WALL'],
        "I0051" : ['Obtain Red Nether Brick Stairs', 'red_nether_brick_stairs', False, 4, 'OBTAIN_RED_NETHER_BRICK_STAIRS'],
        "I0052" : ['Obtain Mushroom Stem', 'mushroom_stem', False, 5, ''],
        "I0053" : ['Obtain Powder Snow Bucket', 'powder_snow_bucket', False, 3, 'OBTAIN_POWDER_SNOW_BUCKET'],
        "I0054" : ['Obtain Scaffolding', 'scaffolding', False, 3, 'OBTAIN_SCAFFOLDING'],
        "I0055" : ['Obtain Soul Lantern', 'soul_lantern', False, 3, 'OBTAIN_SOUL_LANTERN'],
        "I0056" : ['Obtain Bucket of Tropical Fish', 'tropical_fish_bucket', False, 3, 'OBTAIN_TROPICAL_FISH_BUCKET'],
        "I0057" : ['Obtain Wither Skeleton Skull', 'wither_skeleton_skull', False, 5, 'OBTAIN_WITHER_SKELETON_SKULL'],
        "I0058" : ['Obtain Trident', 'trident', False, 7, ''],
        "I0059" : ['Obtain Nautilus Shell', 'nautilus_shell', False, 5, ''],
        "I0060" : ['Obtain Heart of the Sea', 'heart_of_the_sea', False, 2, 'OBTAIN_HEART_OF_THE_SEA'],
        "I0061" : ['Obtain Banner Pattern', 'creeper_banner_pattern', False, 1, ''],
        "I0062" : ['Obtain Rabbit Foot', 'rabbit_foot', False, 4, ''],
        "I0063" : ['Obtain Totem of Undying', 'totem_of_undying', False, 6, ''],
        "I0064" : ['Obtain Name Tag', 'name_tag', False, 4, ''],
        "I0065" : ['Obtain Written Book', 'written_book', False, 3, 'OBTAIN_WRITTEN_BOOK'],
        "I0066" : ['Obtain Bookshelf', 'bookshelf', False, 2, 'OBTAIN_BOOKSHELF'],
        "I0067" : ['Obtain Sea Lantern', 'sea_lantern', False, 4, 'OBTAIN_SEA_LANTERN'],
        "I0068" : ['Obtain Flowering Azalea', 'flowering_azalea', False, 2, 'OBTAIN_FLOWERING_AZALEA'],
        "I0069" : ['Obtain Bell', 'bell', False, 2, 'OBTAIN_BELL'],
        "I0070" : ['Obtain Ancient Debris', 'ancient_debris', False, 4, 'OBTAIN_ANCIENT_DEBRIS'],
        "I0071" : ['Obtain Lodestone', 'lodestone', False, 3, ''],
        "I0072" : ['Obtain Sponge', 'sponge', False, 4, 'OBTAIN_SPONGE'],
        "I0073" : ['Obtain TNT', 'tnt', False, 1, 'OBTAIN_TNT'],
        "I0074" : ['Obtain Goat Horn', 'goat_horn', False, 4, 'TOOT_GOAT_HORN'],
        "I0075" : ['Obtain Daylight Detector', 'daylight_detector', False, 3, 'OBTAIN_DAYLIGHT_DETECTOR'],
        "I0076" : ['Obtain Observer', 'observer', False, 3, 'OBTAIN_OBSERVER'],
        "I0077" : ['Obtain Piston', 'piston', False, 2, 'OBTAIN_PISTON'],
        "I0078" : ['Obtain Sticky Piston', 'sticky_piston', False, 5, ''],
        "I0079" : ['Obtain Tinted Glass', 'tinted_glass', False, 2, 'OBTAIN_TINTED_GLASS'],
        "I0080" : ['Obtain Sniffer Egg', 'sniffer_egg', False, 5, ''],
        "I0081" : ['Obtain Nether Star', 'nether_star', False, 10, ''],
        "I0082" : ['Obtain Netherite Ingot', 'netherite_ingot', False, 6, ''],
        "I0083" : ['Obtain Glow Item Frame', 'glow_item_frame', False, 2, ''],
        "I0084" : ['Obtain Block of Dried Kelp', 'dried_kelp_block', False, 1, ''],
        "I0085" : ['Obtain Elytra', 'elytra', False, 9, ''],
        "I0086" : ['Obtain Turtle Scute', 'turtle_scute', False, 7, ''],
        "I0087" : ['Obtain Glow Lichen', 'glow_lichen', False, 1, ''],
        "I0088" : ['Obtain Flower Pot', 'flower_pot', False, 1, ''],
        "I0089" : ['Obtain Iron Bars', 'iron_bars', False, 1, ''],
        "I0090" : ['Obtain Clock', 'clock', False, 1, 'OBTAIN_CLOCK'],
        "I0091" : ['Brew Swiftness Potion', 'potion', True, 6, 'BREW_SWIFTNESS_POTION'],
        "I0092" : ['Brew Healing Potion', 'potion', True, 6, 'BREW_HEALING_POTION'],
        "I0093" : ['Brew Invisibility Potion', 'potion', True, 6, 'BREW_INVISIBILITY_POTION'],
        "I0094" : ['Brew Jump Boost Potion', 'potion', True, 6, 'BREW_JUMP_BOOST_POTION'],
        "I0095" : ['Obtain Recovery Compass', 'recovery_compass', False, 5, ''],
        "I0096" : ['Obtain Mud Brick Wall', 'mud_brick_wall', False, 2, 'OBTAIN_MUD_BRICK_WALL'],
        "I0097" : ['Obtain Froglight', 'pearlescent_froglight', False, 4, ''],
        "I0098" : ['Obtain All Froglights', 'pearlescent_froglight', True, 8, ''],
        "I0099" : ['Obtain Fermented Spider Eye', 'fermented_spider_eye', False, 3, ''],
        "I0100" : ['Obtain Brush', 'brush', False, 1, ''],
        "I0101" : ['Obtain Armadillo Scute', 'armadillo_scute', False, 2, ''],
        "I0102" : ['Apply 3 Unique Armor Trims', 'coast_armor_trim_smithing_template', True, 4, ''],
        "I0103" : ['Apply 5 Unique Armor Trims', 'rib_armor_trim_smithing_template', True, 6, ''],
        "I0104" : ['Apply 7 Unique Armor Trims', 'silence_armor_trim_smithing_template', True, 8, ''],
        "I0105" : ['Obtain Mace', 'mace', False, 10, ''],
        "I0106" : ['Obtain Creaking Heart', 'creaking_heart', False, 6, ''],
        "I0107" : ['Obtain Resin Brick Stairs', 'resin_brick_stairs', False, 3, 'OBTAIN_RESIN_BRICK_STAIR'],
        "I0108" : ['Obtain All Copper Tools', 'copper_pickaxe', True, 1, 'OBTAIN_COPPER_TOOLS'],
        "I0109" : ['Obtain Full Copper Armor', 'copper_chestplate', True, 2, 'WEAR_COPPER_ARMOR'],
        "I0110" : ['Obtain Dried Ghast', 'dried_ghast', False, 3, ''],
        "I0111" : ['Obtain All Spears', 'netherite_spear', False, 6, ''],
        "I0112" : ['Obtain Any Nautilus Armor', 'iron_nautilus_armor', False, 5, 'OBTAIN_ANY_NAUTILUS_ARMOR'],
        "I0113" : ['Brew Poison Potion', '', False, 6, 'BREW_POISON_POTION'],
        "I0114" : ['Brew Weakness Potion', '', False, 5, 'BREW_WEAKNESS_POTION'],
        "I0115" : ['Brew Water Breathing Potion', '', False, 5, 'BREW_WATER_BREATHING_POTION'],
        "I0116" : ['Brew Lingering Potion', '', False, 5, 'BREW_LINGERING_POTION'],
        "I0117" : ['Obtain Smooth Quartz Stairs', '', False, 3, 'OBTAIN_SMOOTH_QUARTZ_STAIRS'],
        # "I0118" : ['', '', False, 3, ''],
        "I0119" : ['Obtain Dragon Egg', '', False, 8, 'OBTAIN_DRAGON_EGG'],
        # "I0120" : ['', '', False, 6, ''],
        "I0121" : ['Obtain Activator Rail', '', False, 3, 'OBTAIN_ACTIVATOR_RAIL'],
        "I0122" : ['Obtain Detector Rail', '', False, 3, 'OBTAIN_DETECTOR_RAIL'],
        "I0123" : ['Obtain Powered Rail', '', False, 3, 'OBTAIN_POWERED_RAIL'],
        "I0124" : ['Obtain Dispenser', '', False, 2, 'OBTAIN_DISPENSER'],
        "I0125" : ['Obtain Calibrated Sculk Sensor', '', False, 5, 'OBTAIN_CALIBRATED_SCULK_SENSOR'],
        "I0126" : ['Obtain Soul Campfire', '', False, 3, 'OBTAIN_SOUL_CAMPFIRE'],
        "I0127" : ['Obtain Brick Wall', '', False, 1, 'OBTAIN_BRICK_WALL'],
        "I0128" : ['Obtain Dead Bush', '', False, 1, 'OBTAIN_DEAD_BUSH'],
        "I0129" : ['Obtain Experience Bottle', '', False, 3, 'OBTAIN_ENCHANT_BOTTLE'],
        "I0130" : ['Obtain 64 Arrows', '', False, 2, 'OBTAIN_64_ARROWS'],
        "I0131" : ['Obtain 4 Unique Saplings', '', False, 1, 'OBTAIN_4_UNIQUE_SAPLINGS'],
        "I0132" : ['Obtain 6 Unique Flowers', '', False, 1, 'OBTAIN_6_UNIQUE_FLOWERS'],
        # "I0133" : ['Obtain 64 Colored Wool', '', False, 1, 'OBTAIN_64_COLORED_WOOL'],
        "I0134" : ['Obtain 5 Unique Pressure Plates', '', False, 2, 'OBTAIN_5_UNIQUE_PRESSURE_PLATES'],
        "I0135" : ['Obtain 8 Unique Bricks', '', False, 3, 'OBTAIN_8_UNIQUE_BRICKS'],
        "I0136" : ['Obtain 6 Unique Buckets', '', False, 4, 'OBTAIN_6_UNIQUE_BUCKETS'],
        "I0137" : ['Obtain 7 Unique Workstations', '', False, 2, 'OBTAIN_7_UNIQUE_WORKSTATIONS'],
        "I0138" : ['Obtain All Dyes', '', False, 4, 'OBTAIN_ALL_DYES'],
        "I0139" : ['Wear Unique Colored Leather Armor', '', False, 2, 'WEAR_UNIQUE_COLORED_LEATHER_ARMOR'],
        "I0140" : ['Wear Full Enchanted Armor', '', False, 4, 'WEAR_FULL_ENCHANTED_ARMOR'],
        "I0141" : ['Fill Inventory with Unique Items', '', False, 1, 'FILL_INVENTORY_UNIQUE_ITEMS'],
        "I0142" : ['Obtain 32 Arrows', '', False, 1, 'OBTAIN_32_ARROWS'],
        "I0143" : ['Obtain Bone Block', '', False, 1, 'OBTAIN_BONE_BLOCK'],
        "I0144" : ['Obtain Dried Kelp Block', '', False, 1, 'OBTAIN_DRIED_KELP_BLOCK'],
        "I0145" : ['Obtain Emerald Block', '', False, 2, 'OBTAIN_EMERALD_BLOCK'],
        "I0146" : ['Obtain Every Torch Variant', '', False, 3, 'OBTAIN_EVERY_TORCH_VARIANT'],
        "I0147" : ['Obtain Gilded Blackstone', '', False, 3, 'OBTAIN_GILDED_BLACKSTONE'],
        "I0148" : ['Obtain Netherite Scrap', '', False, 3, 'OBTAIN_NETHERITE_SCRAP'],
        "I0149" : ['Obtain Pottery Sherd', '', False, 2, 'OBTAIN_POTTERY_SHERD'],
        "I0150" : ['Obtain Hanging Sign', '', False, 1, 'OBTAIN_HANGING_SIGN'],
        "I0151" : ['Obtain 3 Unique Banner Patterns', '', False, 2, 'OBTAIN_3_UNIQUE_BANNER_PATTERNS'],
        "I1001" : ['Obtain Music Disc 5', 'music_disc_5', False, 6, ''],
        "I1002" : ['Obtain Music Disc 11', 'music_disc_11', False, 5, ''],
        "I1003" : ['Obtain Music Disc 13', 'music_disc_13', False, 4, ''],
        "I1004" : ['Obtain Music Disc Blocks', 'music_disc_blocks', False, 5, ''],
        "I1005" : ['Obtain Music Disc Cat', 'music_disc_cat', False, 2, ''],
        "I1006" : ['Obtain Music Disc Chirp', 'music_disc_chirp', False, 7, ''],
        "I1007" : ['Obtain Music Disc Creator', 'music_disc_creator', False, 4, ''],
        "I1008" : ['Obtain Creator Music Box', 'music_disc_creator_music_box', False, 4, ''],
        "I1009" : ['Obtain Music Disc Far', 'music_disc_far', False, 5, ''],
        "I1010" : ['Obtain Music Disc Mall', 'music_disc_mall', False, 5, ''],
        "I1011" : ['Obtain Music Disc Mellohi', 'music_disc_mellohi', False, 5, ''],
        "I1012" : ['Obtain Music Disc Otherside', 'music_disc_otherside', False, 6, ''],
        "I1013" : ['Obtain Music Disc Pigstep', 'music_disc_pigstep', False, 5, ''],
        "I1014" : ['Obtain Music Disc Precipice', 'music_disc_precipice', False, 5, ''],
        "I1015" : ['Obtain Music Disc Relic', 'music_disc_relic', False, 7, ''],
        "I1016" : ['Obtain Music Disc Stal', 'music_disc_stal', False, 5, ''],
        "I1017" : ['Obtain Music Disc Strad', 'music_disc_strad', False, 5, ''],
        "I1018" : ['Obtain Music Disc Wait', 'music_disc_wait', False, 5, ''],
        "I1019" : ['Obtain Music Disc Ward', 'music_disc_ward', False, 5, ''],
        "I2001" : ['Obtain 64 White Concrete', 'white_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2002" : ['Obtain 64 Pink Concrete', 'pink_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2003" : ['Obtain 64 Magenta Concrete', 'magenta_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2004" : ['Obtain 64 Red Concrete', 'red_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2005" : ['Obtain 64 Orange Concrete', 'orange_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2006" : ['Obtain 64 Yellow Concrete', 'yellow_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2007" : ['Obtain 64 Lime Concrete', 'lime_concrete', False, 3, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2008" : ['Obtain 64 Green Concrete', 'green_concrete', False, 3, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2009" : ['Obtain 64 Cyan Concrete', 'cyan_concrete', False, 3, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2010" : ['Obtain 64 Light Blue Concrete', 'light_blue_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2011" : ['Obtain 64 Blue Concrete', 'blue_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2012" : ['Obtain 64 Purple Concrete', 'purple_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2013" : ['Obtain 64 Brown Concrete', 'brown_concrete', False, 3, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2014" : ['Obtain 64 Light Gray Concrete', 'light_gray_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2015" : ['Obtain 64 Gray Concrete', 'gray_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I2016" : ['Obtain 64 Black Concrete', 'black_concrete', False, 1, 'OBTAIN_64_COLORED_CONCRETE'],
        "I3001" : ['Obtain White Glazed Terracotta', 'white_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3002" : ['Obtain Pink Glazed Terracotta', 'pink_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3003" : ['Obtain Magenta Glazed Terracotta', 'magenta_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3004" : ['Obtain Red Glazed Terracotta', 'red_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3005" : ['Obtain Orange Glazed Terracotta', 'orange_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3006" : ['Obtain Yellow Glazed Terracotta', 'yellow_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3007" : ['Obtain Lime Glazed Terracotta', 'lime_glazed_terracotta', False, 3, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3008" : ['Obtain Green Glazed Terracotta', 'green_glazed_terracotta', False, 3, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3009" : ['Obtain Cyan Glazed Terracotta', 'cyan_glazed_terracotta', False, 3, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3010" : ['Obtain Light Blue Glazed Terracotta', 'light_blue_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3011" : ['Obtain Blue Glazed Terracotta', 'blue_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3012" : ['Obtain Purple Glazed Terracotta', 'purple_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3013" : ['Obtain Brown Glazed Terracotta', 'brown_glazed_terracotta', False, 3, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3014" : ['Obtain Light Gray Glazed Terracotta', 'light_gray_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3015" : ['Obtain Gray Glazed Terracotta', 'gray_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I3016" : ['Obtain Black Glazed Terracotta', 'black_glazed_terracotta', False, 1, 'OBTAIN_COLORED_GLAZED_TERRACOTTA'],
        "I4001" : ['Obtain White Candle', 'white_candle', False, 1, ''],
        "I4002" : ['Obtain Pink Candle', 'pink_candle', False, 1, ''],
        "I4003" : ['Obtain Magenta Candle', 'magenta_candle', False, 1, ''],
        "I4004" : ['Obtain Red Candle', 'red_candle', False, 1, ''],
        "I4005" : ['Obtain Orange Candle', 'orange_candle', False, 1, ''],
        "I4006" : ['Obtain Yellow Candle', 'yellow_candle', False, 1, ''],
        "I4007" : ['Obtain Lime Candle', 'lime_candle', False, 3, ''],
        "I4008" : ['Obtain Green Candle', 'green_candle', False, 3, ''],
        "I4009" : ['Obtain Cyan Candle', 'cyan_candle', False, 3, ''],
        "I4010" : ['Obtain Light Blue Candle', 'light_blue_candle', False, 1, ''],
        "I4011" : ['Obtain Blue Candle', 'blue_candle', False, 1, ''],
        "I4012" : ['Obtain Purple Candle', 'purple_candle', False, 1, ''],
        "I4013" : ['Obtain Brown Candle', 'brown_candle', False, 3, ''],
        "I4014" : ['Obtain Light Gray Candle', 'light_gray_candle', False, 1, ''],
        "I4015" : ['Obtain Gray Candle', 'gray_candle', False, 1, ''],
        "I4016" : ['Obtain Black Candle', 'black_candle', False, 1, ''],
        "I5001" : ['Obtain White Stained Glass', 'white_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5002" : ['Obtain Pink Stained Glass', 'pink_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5003" : ['Obtain Magenta Stained Glass', 'magenta_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5004" : ['Obtain Red Stained Glass', 'red_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5005" : ['Obtain Orange Stained Glass', 'orange_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5006" : ['Obtain Yellow Stained Glass', 'yellow_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5007" : ['Obtain Lime Stained Glass', 'lime_stained_glass', False, 3, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5008" : ['Obtain Green Stained Glass', 'green_stained_glass', False, 3, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5009" : ['Obtain Cyan Stained Glass', 'cyan_stained_glass', False, 3, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5010" : ['Obtain Light Blue Stained Glass', 'light_blue_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5011" : ['Obtain Blue Stained Glass', 'blue_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5012" : ['Obtain Purple Stained Glass', 'purple_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5013" : ['Obtain Brown Stained Glass', 'brown_stained_glass', False, 3, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5014" : ['Obtain Light Gray Stained Glass', 'light_gray_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5015" : ['Obtain Gray Stained Glass', 'gray_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I5016" : ['Obtain Black Stained Glass', 'black_stained_glass', False, 1, 'OBTAIN_COLORED_STAINED_GLASS'],
        "I6001" : ['Obtain 64 White Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6002" : ['Obtain 64 Pink Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6003" : ['Obtain 64 Magenta Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6004" : ['Obtain 64 Red Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6005" : ['Obtain 64 Orange Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6006" : ['Obtain 64 Yellow Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6007" : ['Obtain 64 Lime Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6008" : ['Obtain 64 Green Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6009" : ['Obtain 64 Aqua Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6010" : ['Obtain 64 Light Blue Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6011" : ['Obtain 64 Blue Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6012" : ['Obtain 64 Purple Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6013" : ['Obtain 64 Brown Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6014" : ['Obtain 64 Light Gray Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6015" : ['Obtain 64 Gray Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "I6016" : ['Obtain 64 Black Wool', '', False, 2, 'OBTAIN_64_COLORED_WOOL'],
        "K0001" : ['Kill Bat', 'iron_sword', True, 1, 'KILL_BAT'],
        "K0002" : ['Kill Bee', 'iron_sword', True, 1, 'KILL_BEE'],
        "K0003" : ['Kill Blaze', 'iron_sword', True, 4, 'KILL_BLAZE'],
        "K0004" : ['Kill Cave Spider', 'iron_sword', True, 4, 'KILL_CAVE_SPIDER'],
        "K0005" : ['Kill Drowned', 'iron_sword', True, 2, 'KILL_DROWNED'],
        "K0006" : ['Kill Elder Guardian', 'iron_sword', True, 4, 'KILL_ELDER_GUARDIAN'],
        "K0007" : ['Kill Ender Dragon', 'dragon_head', True, 8, 'KILL_ENDER_DRAGON'],
        "K0008" : ['Kill Endermite', 'iron_sword', True, 6, 'KILL_ENDERMITE'],
        "K0009" : ['Kill Evoker', 'iron_sword', True, 7, 'KILL_EVOKER'],
        "K0010" : ['Kill Ghast', 'iron_sword', True, 3, 'KILL_GHAST'],
        "K0011" : ['Kill Guardian', 'iron_sword', True, 4, 'KILL_GUARDIAN'],
        "K0012" : ['Kill Husk', 'iron_sword', True, 4, 'KILL_HUSK'],
        "K0013" : ['Kill Magma Cube', 'iron_sword', True, 2, 'KILL_MAGMA_CUBE'],
        "K0014" : ['Kill Piglin Brute', 'iron_sword', True, 5, 'KILL_PIGLIN_BRUTE'],
        "K0015" : ['Kill Pillager', 'iron_sword', True, 4, 'KILL_PILLAGER'],
        "K0016" : ['Kill Player', 'diamond_sword', True, 3, 'KILL_OTHER_PLAYER'],
        "K0017" : ['Kill Ravager', 'iron_sword', True, 6, 'KILL_RAVAGER'],
        "K0018" : ['Kill Shulker', 'iron_sword', True, 9, 'KILL_SHULKER'],
        "K0019" : ['Kill Silverfish', 'iron_sword', True, 5, 'KILL_SILVERFISH'],
        "K0020" : ['Kill Slime', 'iron_sword', True, 4, 'KILL_SLIME'],
        "K0021" : ['Kill Snow Golem', 'iron_sword', True, 3, 'KILL_SNOW_GOLEM'],
        "K0022" : ['Kill Spider', 'iron_sword', True, 1, 'KILL_SPIDER'],
        "K0023" : ['Kill Stray', 'iron_sword', True, 4, 'KILL_STRAY'],
        "K0024" : ['Kill Vex', 'iron_sword', True, 7, 'KILL_VEX'],
        "K0025" : ['Kill Witch', 'iron_sword', True, 4, 'KILL_WITCH'],
        "K0026" : ['Kill Wither Skeleton', 'iron_sword', True, 4, 'KILL_WITHER_SKELETON'],
        "K0027" : ['Kill Zoglin', 'iron_sword', True, 5, 'KILL_ZOGLIN'],
        "K0028" : ['Kill Zombie Villager', 'iron_sword', True, 4, 'KILL_ZOMBIE_VILLAGER'],
        "K0029" : ['Kill Zombie', 'iron_sword', True, 1, 'KILL_ZOMBIE'],
        "K0030" : ['Kill Zombified Piglin', 'iron_sword', True, 2, 'KILL_ZOMBIFIED_PIGLIN'],
        "K0031" : ['Kill 30 Mobs', 'iron_sword', True, 1, ''],
        "K0032" : ['Kill 100 Mobs', 'iron_sword', True, 2, 'KILL_100_MOBS'],
        "K0033" : ['Kill 30 Undead Mobs', '', False, 2, 'KILL_30_UNDEAD_MOBS'],
        "K0034" : ['Kill 20 Arthropod Mobs ', '', False, 2, 'KILL_20_ARTHROPOD_MOBS'],
        "K0035" : ['Kill 10 Unique Hostile Mobs', '', False, 3, 'KILL_10_UNIQUE_HOSTILE_MOBS'],
        "K0036" : ['Kill 13 Unique Hostile Mobs', '', False, 4, 'KILL_13_UNIQUE_HOSTILE_MOBS'],
        "K0037" : ['Kill 7 Unique Hostile Mobs', 'iron_sword', True, 3, 'KILL_7_UNIQUE_HOSTILE_MOBS'],
        "K0038" : ['Kill 15 Unique Hostile Mobs', 'iron_sword', True, 5, 'KILL_15_UNIQUE_HOSTILE_MOBS'],
        "K0039" : ['Kill Snow Golem in Nether', '', False, 4, 'KILL_SNOW_GOLEM_IN_NETHER'],
        "K0040" : ['Kill All Raid Mobs', '', False, 7, 'KILL_ALL_RAID_MOBS'],
        "K0041" : ['Kill Warden', 'iron_sword', True, 8, 'KILL_WARDEN'],
        "K0042" : ['Kill Bogged', 'iron_sword', True, 4, 'KILL_BOGGED'],
        "K0043" : ['Kill Breeze', 'iron_sword', True, 4, 'KILL_BREEZE'],
        "K0044" : ['Kill Breeze Using Wind Charge', '', False, 4, 'KILL_BREEZE_USING_WIND_CHARGE'],
        "K0045" : ['Kill Blaze With Snowball', '', False, 4, 'KILL_BLAZE_WITH_SNOWBALL'],
        "K1001" : ['Kill White Sheep', 'white_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1002" : ['Kill Pink Sheep', 'pink_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1003" : ['Kill Magenta Sheep', 'magenta_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1004" : ['Kill Red Sheep', 'red_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1005" : ['Kill Orange Sheep', 'orange_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1006" : ['Kill Yellow Sheep', 'yellow_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1007" : ['Kill Lime Sheep', 'lime_wool', True, 3, 'KILL_COLORED_SHEEP'],
        "K1008" : ['Kill Green Sheep', 'green_wool', True, 3, 'KILL_COLORED_SHEEP'],
        "K1009" : ['Kill Cyan Sheep', 'cyan_wool', True, 3, 'KILL_COLORED_SHEEP'],
        "K1010" : ['Kill Light Blue Sheep', 'light_blue_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1011" : ['Kill Blue Sheep', 'blue_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1012" : ['Kill Purple Sheep', 'purple_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1013" : ['Kill Brown Sheep', 'brown_wool', True, 3, 'KILL_COLORED_SHEEP'],
        "K1014" : ['Kill Light Gray Sheep', 'light_gray_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1015" : ['Kill Gray Sheep', 'gray_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "K1016" : ['Kill Black Sheep', 'black_wool', True, 1, 'KILL_COLORED_SHEEP'],
        "M0006" : ['Have the Most Deaths', 'diamond_sword', True, 3, ''],
        "M0007" : ['Have the Most Advancements', 'experience_bottle', True, 3, 'HAVE_MOST_ADVANCEMENTS'],
        "M0008" : ['Have the Most Unique Breeds', 'wheat', True, 3, ''],
        "M0009" : ['Eat the Most Unique Foods', 'apple', True, 3, ''],
        "M0010" : ['Apply the Most Unique Armor Trims', 'coast_armor_trim_smithing_template', True, 3, ''],
        "M0011" : ['Kill the Most Unique Hostile Mobs', 'iron_sword', True, 3, ''],
        "M0012" : ['Have the Most Dried Kelp Blocks', 'dried_kelp_block', True, 3, ''],
        "M0013" : ['Have the Most Hoppers', 'hopper', True, 3, 'HAVE_MOST_HOPPERS'],
        "M0014" : ['Have the Most Levels', 'experience_bottle', True, 3, 'HAVE_MORE_XP_LEVELS'],
        "M0015" : ['Have the Most Unique Crafts', 'crafting_table', True, 3, 'HAVE_MORE_UNIQUE_CRAFTS'],
        "M0016" : ['Have the Most Player Kills', '', False, 1, 'HAVE_MOST_PLAYER_KILLS'],
        "M0017" : ['Have the Most Leaflitter', '', False, 1, 'HAVE_MOST_LEAFLITTER'],
        "M0018" : ['Have the Most Diamond Blocks', '', False, 3, 'HAVE_MOST_DIAMOND_BLOCKS'],
        "N0001" : ['Opponent Obtains Crafting Table', 'barrier', True, 2, 'OPPONENT_OBTAINS_CRAFTING_TABLE'],
        "N0002" : ['Opponent Obtains Obsidian', 'barrier', True, 2, 'OPPONENT_OBTAINS_OBSIDIAN'],
        "N0003" : ['Opponent Obtains Seeds', 'barrier', True, 2, 'OPPONENT_OBTAINS_SEEDS'],
        "N0004" : ['Opponent Eats', 'barrier', True, 2, 'OPPONENT_EATS_FOOD'],
        "N0005" : ['Opponent Obtains Advancement', 'barrier', True, 4, 'OPPONENT_OBTAINS_ADVANCEMENT'],
        "N0006" : ['Opponent Gets 5 Levels', 'barrier', True, 4, 'OPPONENT_GETS_5_LEVELS'],
        "N0007" : ['Opponent Touches Water', 'barrier', True, 3, 'OPPONENT_TOUCHES_WATER'],
        "N0008" : ['Opponent Stands on Netherrack', 'barrier', True, 4, 'OPPONENT_STANDS_ON_NETHERRACK'],
        "N0009" : ['Opponent Stands on Stone', 'barrier', True, 4, 'OPPONENT_STANDS_ON_STONE'],
        "N0010" : ['Opponent Wears Armor', 'barrier', True, 4, 'OPPONENT_WEARS_ARMOR'],
        "N0011" : ['Opponent Dies', 'barrier', True, 2, 'OPPONENT_DIES'],
        "N0012" : ['Opponent Dies 3 Times', 'barrier', True, 2, 'OPPONENT_DIES_3_TIMES'],
        "N0013" : ['Opponent Takes 100 Damage', 'barrier', True, 2, 'OPPONENT_TAKES_100_DAMAGE'],
        "N0014" : ['Opponent Takes Fall Damage', 'barrier', True, 2, 'OPPONENT_TAKES_FALL_DAMAGE'],
        "N0015" : ['Opponent Catches Fire', 'barrier', True, 2, 'OPPONENT_CATCHES_ON_FIRE'],
        "N0016" : ['Opponent Hit by Egg', '', False, 1, 'OPPONENT_HIT_BY_EGG'],
        "N0017" : ['Opponent Hit by Snowball', '', False, 1, 'OPPONENT_HIT_BY_SNOWBALL'],
        "N0018" : ['Opponent Hit by Arrow', '', False, 1, 'OPPONENT_HIT_BY_ARROW'],
        "R0001" : ['Ride Horse', 'saddle', False, 2, 'RIDE_HORSE'],
        "R0002" : ['Ride Nautlius', 'saddle', False, 3, 'RIDE_NAUTILUS'],
        "R0003" : ['Ride Minecart', 'minecart', False, 2, 'RIDE_MINECART'],
        "R0004" : ['Ride Pig', 'saddle', False, 2, 'RIDE_PIG'],
        "T0001" : ['Tame Cat', 'cod', True, 2, 'TAME_CAT'],
        "T0002" : ['Tame Wolf', 'bone', True, 2, 'TAME_WOLF'],
        "T0003" : ['Tame Horse', 'golden_carrot', True, 2, 'TAME_HORSE'],
        "T0004" : ['Tame Donkey', 'golden_carrot', True, 3, 'TAME_DONKEY'],
        "T0005" : ['Tame Mule', 'golden_carrot', True, 5, 'TAME_MULE'],
        "T0006" : ['Tame Parrot', 'melon_seeds', True, 4, 'TAME_PARROT'],
        "T0007" : ['Tame Llama', 'hay_block', True, 4, ''],
        "T0009" : ['Tame Every Cat Variant', 'cod', True, 9, ''],
        "T0010" : ['Tame Nautilus', 'nautilus_shell', False, 2, 'TAME_NAUTILUS'],
        "X0001" : ['Get 5 Levels', 'experience_bottle', True, 1, ''],
        "X0002" : ['Get 15 Levels', 'experience_bottle', True, 2, 'REACH_EXP_LEVEL_15'],
        "X0003" : ['Get 30 Levels', 'experience_bottle', True, 4, 'REACH_EXP_LEVEL_30'],
        "X0004" : ['Mine Diamond', 'diamond_ore', False, 2, 'MINE_DIAMOND_ORE'],
        "X0005" : ['Mine Emerald Ore', 'emerald_ore', False, 3, 'MINE_EMERALD_ORE'],
        "X0006" : ['Mine Mob Spawner', 'spawner', False, 2, 'MINE_MOB_SPAWNER'],
        "X0007" : ['Get 64 of the Same Item', 'dirt', True, 1, ''],
        "X0008" : ['Sprint 1km', 'diamond_boots', True, 1, 'SPRINT_1_KM'],
        "X0009" : ['Wear a Pumpkin for 5 Minutes', 'carved_pumpkin', True, 2, 'WEAR_CARVED_PUMPKIN_FOR_5_MINUTES'],
        "X0010" : ['Take 200 Damage', 'wooden_sword', True, 1, 'TAKE_200_DAMAGE'],
        "X0011" : ['Empty Hunger Bar', 'rotten_flesh', True, 1, 'EMPTY_HUNGER_BAR'],
        "X0012" : ['Wash Leather Armor', 'cauldron', True, 2, ''],
        "X0013" : ['Use a Jukebox', 'jukebox', False, 3, 'USE_JUKEBOX'],
        "X0014" : ['Reach Bedrock', 'bedrock', False, 1, 'REACH_BEDROCK'],
        "X0015" : ['Reach Height Limit', 'glass', True, 1, 'REACH_HEIGHT_LIMIT'],
        "X0016" : ['Travel to Nether Roof', 'bedrock', False, 2, 'REACH_NETHER_ROOF'],
        "X0017" : ['Locate Woodland Mansion', 'red_carpet', False, 4, ''],
        "X0018" : ['Have 3 Status Effects at Once', 'milk_bucket', True, 1, 'GET_3_STATUS_EFFECTS_AT_ONCE'],
        "X0019" : ['Have 6 Status Effects at Once', 'milk_bucket', True, 4, 'GET_6_STATUS_EFFECTS_AT_ONCE'],
        "X0020" : ['Have 9 Status Effects at Once', 'milk_bucket', True, 6, ''],
        "X0021" : ['Have 12 Status Effects at Once', 'milk_bucket', True, 8, ''],
        "X0022" : ['Craft 25 Unique Items', 'crafting_table', True, 1, ''],
        "X0023" : ['Craft 50 Unique Items', 'crafting_table', True, 2, ''],
        "X0024" : ['Craft 75 Unique Items', 'crafting_table', True, 4, ''],
        "X0025" : ['Find an Ancient City', 'sculk_shrieker', False, 2, ''],
        "X0026" : ['Locate Trail Ruins', 'brush', False, 3, ''],
        "X0027" : ['Trade With Master Villager', 'emerald', True, 4, ''],
        "X0028" : ['Locate Badlands Biome', '', False, 2, 'VISIT_BADLANDS_BIOME'],
        "X0029" : ['Locate Ice Spikes Biome', '', False, 2, 'VISIT_ICE_SPIKES_BIOME'],
        "X0030" : ['Locate Mushroom Island', '', False, 2, 'VISIT_MUSHROOM_BIOME'],
        "X0031" : ['Locate 10 Unique Biomes', '', False, 1, 'VISIT_10_UNIQUE_BIOMES'],
        "X0032" : ['Locate 15 Unique Biomes', '', False, 2, 'VISIT_15_UNIQUE_BIOMES'],
        "X0033" : ['Locate 20 Unique Biomes', '', False, 3, 'VISIT_20_UNIQUE_BIOMES'],
        "X0034" : ['Mine Turtie Egg', '', False, 2, 'MINE_TURTLE_EGG'],
        "X0035" : ['Mine Crafter', '', False, 2, 'MINE_CRAFTER'],
        "X0036" : ['Have Your Shield Disabled', '', False, 3, 'HAVE_YOUR_SHIELD_DISABLED'],
        "X0037" : ['Put Item Frame in Item Frame', '', False, 1, 'ITEM_FRAME_IN_ITEM_FRAME'],
        "X0038" : ['Put Flower in Flower Pot', '', False, 1, 'PUT_FLOWER_IN_POT'],
        "X0039" : ['Fill Campfire', '', False, 1, 'FILL_CAMPFIRE'],
        "X0040" : ['Fill Chiseled Bookshelf', '', False, 1, 'FILL_CHISELED_BOOKSHELF'],
        "X0041" : ['Fill Armor Stand', '', False, 2, 'FILL_ARMOR_STAND'],
        "X0042" : ['Fill Shelf', '', False, 1, 'FILL_SHELF'],
        "X0043" : ['Fill Bundle', '', False, 1, 'FILL_BUNDLE'],
        "X0044" : ['Light Candle', '', False, 2, 'LIGHT_CANDLE'],
        "X0045" : ['Enrage Zombified Piglin', '', False, 2, 'ENRAGE_ZOMBIFIED_PIGLIN'],
        "X0046" : ['Use Brush on Suspicious Sand/Gravel', '', False, 2, 'USE_BRUSH_ON_SUSPICIOUS_BLOCK'],
        "X0047" : ['Use Glow Ink', '', False, 2, 'USE_GLOW_INK'],
        "X0048" : ['Use Loom', '', False, 2, 'USE_LOOM'],
        "X0049" : ['Use Brewing Stand', '', False, 2, 'USE_BREWING_STAND'],
        "X0050" : ['Use Smithing Table', '', False, 3, 'USE_SMITHING_TABLE'],
        "X0051" : ['Use Cauldron', '', False, 2, 'USE_CAULDRON'],
        "X0052" : ['Use Composter', '', False, 1, 'USE_COMPOSTER'],
        "X0053" : ['Use Stonecutter', '', False, 1, 'USE_STONECUTTER'],
        "X0054" : ['Use Anvil', '', False, 3, 'USE_ANVIL'],
        "X0055" : ['Use Grindstone', '', False, 1, 'USE_GRINDSTONE'],
        "X0056" : ['Tune Note Block', '', False, 2, 'TUNE_NOTE_BLOCK'],
        "X0057" : ['Place a Painting', '', False, 1, 'PLACE_PAINTING'],
        "X0058" : ['Break Any Tool', '', False, 1, 'BREAK_TOOL'],
        "X0059" : ['Put Banner on Shield', '', False, 1, 'PUT_BANNER_ON_SHIELD'],
        "X0060" : ['Create Banner Waypoint on Map', '', False, 2, 'MAP_BANNER_WAYPOINT'],
        "X0061" : ['Construct Copper Golem', '', False, 2, 'CONSTRUCT_COPPER_GOLEM'],
        "X0062" : ['Shoot Firework from Crossbow', '', False, 2, 'SHOOT_FIREWORK_FROM_CROSSBOW'],
        "X0063" : ['Place End Crystal', 'end_crystal', False, 4, 'PLACE_END_CRYSTAL'],
        "X0064" : ['Wear Colored Leather Armor Piece', '', False, 1, 'WEAR_COLORED_LEATHER_ARMOR_PIECE'],
        "X0065" : ['Deal 400 Damage', 'stone_axe', False, 1, 'DEAL_400_DAMAGE'],
        "X0066" : ['Boat 2km', 'oak_boat', False, 1, 'BOAT_2_KM'],
        "X0067" : ['Break Any Armor Piece', '', False, 1, 'BREAK_ARMOR_PIECE'],
        "X0068" : ['Compost 3 Unique Foods', 'composter', False, 1, 'COMPOST_3_UNIQUE_FOODS'],
        "X0069" : ['Compost 5 Unique Foods', 'composter', False, 2, 'COMPOST_5_UNIQUE_FOODS'],
        "X0070" : ['Compost 7 Unique Foods', 'composter', False, 3, 'COMPOST_7_UNIQUE_FOODS'],
        # "X0071" : ['', '', False, 1, ''],
        # "X0072" : ['', '', False, 1, ''],
        # "X0073" : ['', '', False, 5, ''],
        # "X0074" : ['', '', False, 5, ''],
        "X1025" : ['Get Absorption', 'golden_apple', True, 2, 'GET_ABSORPTION_STATUS_EFFECT'],
        "X1026" : ['Get Glowing', 'spectral_arrow', True, 2, 'GET_GLOWING_STATUS_EFFECT'],
        "X1027" : ['Get Poisoned', 'spider_eye', True, 1, 'GET_POISON_STATUS_EFFECT'],
        "X1028" : ['Get Nausea', 'pufferfish', True, 3, 'GET_NAUSEA_STATUS_EFFECT'],
        "X1029" : ['Get Leaping', 'rabbit_foot', True, 2, 'GET_JUMP_BOOST_STATUS_EFFECT'],
        "X1030" : ['Get Withered', 'wither_rose', True, 3, 'GET_WITHER_STATUS_EFFECT'],
        "X1031" : ['Get Mining Fatigue', 'wooden_shovel', True, 3, 'GET_MINING_FATIGUE_STATUS_EFFECT'],
        "X1032" : ['Get Blindness', 'suspicious_stew', True, 3, 'GET_BLINDNESS_STATUS_EFFECT'],
        "X1033" : ['Get Strength', 'blaze_powder', True, 5, 'GET_STRENGTH_STATUS_EFFECT'],
        "X1034" : ['Get Fire Resistance', 'magma_cream', True, 4, 'GET_FIRE_RESISTANCE_STATUS_EFFECT'],
        "X1035" : ['Get Water Breathing', 'pufferfish', True, 3, 'GET_WATER_BREATHING_STATUS_EFFECT'],
        "X1036" : ['Get Night Vision', 'golden_carrot', True, 2, 'GET_NIGHT_VISION_STATUS_EFFECT'],
        "X1037" : ['Get Weakness', 'wooden_sword', True, 2, 'GET_WEAKNESS_STATUS_EFFECT'],
        "X1038" : ['Get Levitation', 'shulker_shell', False, 9, 'GET_LEVITATION_STATUS_EFFECT'],
        "X1039" : ['Get Bad Omen', '', False, 5, 'GET_BAD_OMEN_STATUS_EFFECT'],
        "X1040" : ['Remove Status Effect', 'milk_bucket', False, 1, 'REMOVE_STATUS_EFFECT_USING_MILK'],
        "X1041" : ['Have 4 Status Effects at Once', 'milk_bucket', False, 3, 'GET_4_STATUS_EFFECTS_AT_ONCE'],

        # goal ideas
        # "X0034": ['Create Rainbow Sheep', 'nametag', 2],
        # "X0035": ['Summon Johnny', 'nametag', 3],
        # "": ['Obtain Coal Ore', 'coal_ore', 3],

}


def getGoalPoolMeta(poolId):
    try:
        file = open('goal_pools/' + poolId + '.json', 'r')
        goalPool = json.load(file)
        return goalPool['meta']
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print('The specified goal pool,', poolId, ', could not be found or is unreadable.') 
        print(e)
        return None


def parseGoalPool(poolId) -> list:
    try:
        file = open('goal_pools/' + poolId + '.json', 'r')
        goalPool = json.load(file)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print('The specified goal pool,', poolId, ', could not be found or is unreadable.') 
        print(e)
        return []

    goalList = []
    excludedGoals = []

    for pool in goalPool['pools']:
        match pool['type']:
            case 'all':
                for goal in pool['goals']:
                    goalList.append(goal)
            case 'weighted':
                for goal in pool['goals']:
                    pass #TODO: Implement weighted goal parser
            case 'exclude':
                for goal in pool['goals']:
                    excludedGoals.append(goal)
            case 'pick':
                for _ in range(pool['amount']):
                    randomGoal = random.choice(pool['goals'])
                    goalList.append(randomGoal)
                    pool['goals'].remove(randomGoal) #ensure the same goal is not picked twice
            case 'include':
                for goal in parseGoalPool(pool['file']):
                    goalList.append(goal)
            case _:
                continue

    
    for goal in excludedGoals:
        if goal in goalList:
            goalList.remove(goal)

    return goalList
    

def dumpGeneratorInfo():
    message = f'''=====================================================================
Truffle Minecraft Lockout - v{VERSION}
©2026 YouDiedRespawn Studios (GNU GPLv3)
Supports MC {MCVERSION}
Goals: {len(GOAL_INDEX)}

Default Options [Edit in options.txt] -------------------------------
OUTPUT_DIR             = {OUTPUT_DIR}
DEFAULT_MODE           = {DEFAULT_MODE}
DEFAULT_SIZE           = {DEFAULT_SIZE}
DEFAULT_DIFFICULTY     = {DEFAULT_DIFFICULTY}
DEBUG                  = {DEBUG}

LK_START_TIME          = {LK_START_TIME}
LK_MAX_TIME            = {LK_MAX_TIME}
LK_SHOW_PROGRESS       = {LK_SHOW_PROGRESS}
LK_ALLOW_PVP           = {LK_ALLOW_PVP}
LK_ALLOW_FRIENDLY_FIRE = {LK_ALLOW_FRIENDLY_FIRE}
LK_ALLOW_TRACKER       = {LK_ALLOW_TRACKER}
LK_ALLOW_DRAW          = {LK_ALLOW_DRAW}
LK_ALLOW_RESIGN        = {LK_ALLOW_RESIGN}
LK_END_ON_WIN          = {LK_END_ON_WIN}
LK_SHOW_TIMER          = {LK_SHOW_TIMER}
====================================================================='''
    return message

